name: SonarQube Analysis

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:


permissions:
  pull-requests: read
  contents: read


jobs:

  SonarQube:

    runs-on: self-hosted

    steps:

    # Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    # Install .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    # Install SonarScanner for .NET
    - name: Install SonarScanner
      run: |
        dotnet tool install --global dotnet-sonarscanner


    # Start SonarQube analysis
    - name: SonarQube Begin
      run: |
        dotnet sonarscanner begin `
          /k:"SonarCubewithDotNet" `
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"


    # Restore packages
    - name: Restore
      run: |
        dotnet restore SonarCubewithDotNet.sln


    # Build project
    - name: Build
      run: |
        dotnet build SonarCubewithDotNet.sln --no-restore


    # Finish SonarQube analysis
    - name: SonarQube End
      run: |
        dotnet sonarscanner end `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
